name: Docker image (Node)

on:
  push:
    branches:
      - master
    paths:
      - 'nodejs.Dockerfile'
      - 'nodejs.entrypoint.sh'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nodejs:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    strategy:
      fail-fast: false
      matrix:
        node_version: [12, 14, 16, 18, 19, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3

      - name: Login to DockerHub
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@15560696de535e4014efeff63c48f16952e52dd1 # v6
        with:
          build-args: NODE_VERSION=${{ matrix.node_version }}
          context: .
          file: nodejs.Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: djoh/all-in-one:node${{ matrix.node_version }}
          cache-from: type=registry,ref=djoh/all-in-one:buildcache_node${{ matrix.node_version }}
          cache-to: type=registry,ref=djoh/all-in-one:buildcache_node${{ matrix.node_version }},mode=max
